apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow-inkook-kim # kubeflow # both namespace succeed. but kubeflow cannot see graph on gui
  labels:
    controller-tools.k8s.io: "1.0"
  name: fashion-mnist-experiment-5
spec:
  parallelTrialCount: 2  
  maxTrialCount: 4
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99  
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
      - loss
      - Validation-loss
  algorithm:
    algorithmName: random
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: kubeflow-registry.default.svc.cluster.local:30000/katib-job:2250A8E1
                  command: 
                  - "python"
                  - "/app/fashion-mnist-katib.py" 
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                  resources: # here
                    limits:
                      nvidia.com/gpu: 0
                restartPolicy: Never
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.005"
        max: "0.015"
    - name: --dropout_rate
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.9"
#    - name: --opt                # here not match katib source
#      parameterType: int
#      feasibleSpace:
#        min: "0"
#        max: "1" 
